### ISSUE TITLE
Hard to copy cloud credentials on iOS platform

### ISSUE THREAD

**Issue by jlongman** [synchrone/sandstorm-radicale#13]
- Apple's (stupid) selection mechanism will not properly highlight the password as offered by the CardDAV UI:  When the password contains non-alphanumeric characters (e.g. dash, underscore) the selection will not completely select the entire word, and will switch to it's (again, stupid) box selection style and not grab the word.
  - my workaround was to use a VNC session to an OSX box and select it there
- selecting the host and path from the URL is also difficult, but on IOS in the Advanced options it _may_ (nb untested) be possible to cut and paste the entire URL and this will backfill the form.  It might be nice to have the host and path fields also separate.

Sorry I don't have a suggested format - it's easy on OSX to just edit the HTML using Inspect HTML and see whether it's the 'pre' tag causing the weirdness but harder on iOS since that options not available.

**Comment by kentonv** [comment]
@synchrone One way to improve this might be to enable the new clipboard button implemented by @mnutt: set `renderTemplate.clipboardButton` to `left` or `right`.

**Comment by synchrone** [comment]
@kentonv thank you for pointing out there's a clipboardButton feature.
I was thinking about raising an issue for this UI improvement, since there appeared to be no way to get inside the iframe and handle the UI from the app itself.

Worth documenting it somewhere to be [findable via search](https://docs.sandstorm.io/en/latest/search.html?q=clipboardButton)

**Comment by kentonv** [comment]
@synchrone Yeah, the feature is brand new in the latest release and hasn't been documented yet.

**Comment by synchrone** [comment]
Should be solved in v9's 1c3a135446acab796e8b82b3442566d167a6f0a2
