### ISSUE TITLE
Unable to sync addressbook with DAVDroid

### ISSUE THREAD

**Issue by garrison** [synchrone/sandstorm-radicale#18]
I have created an addressbook in Radicale, and I can successfully sync it with Thunderbird.  However, when I try to add it to DAVDroid, I get the error "Resource detection: No address books or calendars were found."  I am able to successfully sync calendars using DAVDroid, but not address books.

Has anybody else experienced this?

My [full debug log is available here](https://gist.github.com/garrison/61722fba557dd826037a).  (Since it includes the URL in the log, I am using a temporary addressbook that I plan to delete.)

**Comment by synchrone** [comment]
It seems to be operating under an assumption that the calendar URL must contain current-user-principal, while I have recently modified it to not, for ACL simplification reasons.

Should be easy enough to fix.

**Comment by synchrone** [comment]
Consider trying [DAVDroid Version 1.0](https://f-droid.org/repository/browse/?fdfilter=dav&fdid=at.bitfire.davdroid), released 2016-03-28? 
It seems to work with v11 on oasis.sandstorm.io

**Comment by garrison** [comment]
Thanks.  I just upgraded to version 1.0 and tried again.  Unfortunately I now get the cryptic error "Unfortunately, DAVdroid has stopped." right after I enter the URL, username, and password.  (If I instead intentionally enter the wrong password, it complains that it "Couldn't find CalDAV or CardDav service.")

**Comment by garrison** [comment]
I got it to work on a different device (an Android tablet). Not sure why my phone is having the issue I mentioned.
