### ISSUE TITLE
Mac OS X Add Account Manual mode claims it cannot authenticate.

### ISSUE THREAD

**Issue by synchrone** [synchrone/sandstorm-radicale#23]
Because of the fact that radicale reports principal url to be `/radicale/readwrite` and the resource URL to be `/radicale/owner/file.ext` - os x add account dialog thinks it's a faulty credentials scenario. If they match - it works just fine, so it's easy to fix by renaming readwrite user to "owner".

However, if I share my calendar with another user - his principal url will never match resource URL (being prefixed with the `owner` user name) with my current principal (e.g `readonly` user).

How to solve this to please os x dav clients - I don't know yet.

**Comment by rajid** [comment]
Why was this closed when it still doesn't work from MacOS X High Sierra?

**Comment by rajid** [comment]
Strange!  After the mac not being synced with the same address book as the iphone, I went away for about 30 minutes, and when I come back they're both seeing the same data now!
