### ISSUE TITLE
Link to Radicale docs instead of hover.com

### ISSUE THREAD

**Issue by mauro3** [synchrone/sandstorm-radicale#24]
The two links at the bottom of the sync-dialog: "How to set up iOS/Android to sync?" and "How to set up Mozilla Thunderbird to sync?" (note that the second link is currently broken) should probably better point to the Radicale docs, e.g.:

http://radicale.org/user_documentation/#idiphone-ipad

http://radicale.org/user_documentation/#idlightning

**Comment by synchrone** [comment]
Fixed in [v14](https://github.com/synchrone/sandstorm-radicale/releases/tag/v14)
