### ISSUE TITLE
Radicale APP security vulnerability issue in Sandstorm platform

### ISSUE THREAD

**Issue by akustolin** [synchrone/sandstorm-radicale#28]
Dear synchrone,
I found a potential security vulnerability in Radicale  with Sandstorm platform.
May I have your e-mail address ?

**Comment by troyjfarrell** [comment]
@akustolin You can find synchrone's contact information by looking at the [Sandstorm app page](https://apps.sandstorm.io/app/8kr4rvyrggvzfvc160htzdt4u5rfvjc2dgdn27n5pt66mxa40m1h) or the [linked Keybase profile](https://keybase.io/synchrone).

**Comment by synchrone** [comment]
@akustolin feel free to write me at syn+sandstorm-radicale@syn.im
