### ISSUE TITLE
Attempt to invoke virtual method 'net.fortuna.ical4j.component.VTimeZone ...

### ISSUE THREAD

**Issue by andreasseiler** [synchrone/sandstorm-radicale#34]
Hey there,

I'm using the CalDAV Sync Adapter on Android and getting the above error after I use the Calendar a while. Can't say when exactly it occurs. 

As the Error states it might have to do something with TimeZones. This is supported by the fact, that in the web GUI of the Radicale app, I see my entries in GMT (I assume its GMT because its 2 hours difference) in the monthly preview and in my correct TimeZone (Europe/Berlin) when I open the detail view. 

Any idea what bug might be behind this? Maybe there is a workaround already?

Thanks,
Andi

**Comment by synchrone** [comment]
looks like a CalDAV Sync Adapter issue. Also the title is not a proper place to put error messages. It got cut in this case, as you can see.
Please post it in full, as a comment or edit the issue to add it.

**Comment by andreasseiler** [comment]
Oh yeah I'm sorry for that, but it didn't get cut. I can't see more of the Error Message on my smartphone ... 

`'net.fortuna.ical4j.component.VTimeZone ...`

;)

**Comment by synchrone** [comment]
sorry, there's too little to go with. Maybe if you could use `logcat` to get the full stack trace I would have a better idea on how to fix it.

**Comment by andreasseiler** [comment]
It appears it's a combination of KOrganizer with the CalDAV Adapter ... Nevermind I'm gonna close this as it is not worth it for me to investigate further. If I use another Desktop client it all seems to work fine. Thanks anyway!!!
