### ISSUE TITLE
Cloud Sync Icon doesn't appear in Contacts

### ISSUE THREAD

**Issue by jlongman** [synchrone/sandstorm-radicale#7]
Having used a github version (v4) before the most recent release of 1.1.1 to sandstorm apps, there used to be a Cloud Sync button which would show the options needed to sync.  (I'm not clear if the sandstorm app is v5 or v6 as the marketing version for both is 1.1.1.)

In 1.1.1 this is missing from view, however an Inspect Elements in a desktop browser permits one to add `style="display:block;"` to the `integration_d` element to make it visible.  It has an (inherited) `display:none` instead.

Tested using MobileSafari on iOS 9, Chrome on iOS, Safari 9.0.3.

**Comment by synchrone** [comment]
Thanks for a bug report.
Fixed via 418d2f8c385d44ace7708c4177c8faab104a38b6
